home/urls.py
from django.conf import settings
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

linekode/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns, set_language
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve

from contact.api import PostContactMessageAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api/v1/messages/', PostContactMessageAPIView.as_view(), name='post-message'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += i18n_patterns(
    path('', include('home.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(domain='djangojs', packages=[
        'home',
        'contact',
        ]), name='javascript-catalog'),
)

contact/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Contact(models.Model):
    first_name = models.CharField(max_length=50, blank=True, null=True,
        verbose_name=_('first name'))
    last_name = models.CharField(max_length=50, blank=True, null=True,
        verbose_name=_('last name'))
    email = models.CharField(max_length=100, blank=False, null=False, unique=True,
        verbose_name=_('email'))
    phone = models.CharField(max_length=15, blank=True, null=True,
        verbose_name=_('phone'))
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    class Meta:
        verbose_name = _('contact')
        verbose_name_plural = _('contacts')

    def get_messages(self):
        return self.messages.all()

    def __str__(self):
        return f'{self.first_name} {self.last_name}: {self.email}'


class ContactMessage(models.Model):
    contact = models.ForeignKey(
        'contact.Contact',
        on_delete=models.CASCADE,
        blank=False,
        null=True,
        related_name='messages',
        verbose_name=_('contact'),
    )
    description = models.TextField(verbose_name=_('description'))
    sent_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('contact message')
        verbose_name_plural = _('contact messages')

contact/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.utils.translation import gettext_lazy as _

from contact.models import Contact, ContactMessage


ContactFormSet = inlineformset_factory(Contact, ContactMessage,
    fields=(
        'first_name',
        'last_name',
        'email',
        'phone',
        'description'
    ),
    extra=1,
)


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'email', 'phone')
        labels = {
            'first_name': _('First name'),
            'last_name': _('Last name'),
            'email': _('Email'),
            'phone': _('Phone'),
        }
        localized_fields = '__all__'

contact/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.conf import settings
from django.views.generic import TemplateView
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import ensure_csrf_cookie

@ensure_csrf_cookie
def home(request):
    return render(request, 'home/home.bundle.html', context={'g_recaptcha_public_key': settings.GOOGLE_RECAPTCHA_PUBLIC_KEY})

contact/templates/contact/snippets/contact_form_snippet.html
{% load i18n %}

<form id="contact-form" action="#" method="POST">
    <h2>{% trans "Tell us about your project" %}</h2>
    <label for="first_name">{% trans "First name(s)" %}
        <input name="first_name" type="text" placeholder="John" autocomplete="given-name" />
    </label>
    <label for="last_name">{% trans "Last name(s)" %}
        <input name="last_name" type="text" placeholder="Doe" autocomplete="family-name" />
    </label>
    <label for="email">{% trans "Email" %}
        <input name="email" type="email" placeholder="john.doe@example.com" autocomplete="email" />
    </label>
    <label for="phone">{% trans "Phone" %}
        <input 
        name="phone" 
        type="tel" 
        placeholder="+1(809)123-4567" 
        autocomplete="tel-national" />
    </label>
    <label for="message">{% trans "Message" %}
        <textarea name="message" type="text" placeholder="{% trans 'Your description here' %}" autocomplete="off"></textarea>
    </label>

    <div class="g-recaptcha" data-sitekey="{{ g_recaptcha_public_key }}"></div>
    <button type="submit">{% trans "Submit" %}</button>
    <button type="reset">{% trans "Clear" %}</button>
</form>

home/templates/home/home.html
{% extends "layout.bundle.html" %}
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %}Linekode | Home{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static '<%= htmlWebpackPlugin.files.chunks.home.css %>' %}">
<link rel="stylesheet" href="{% static '<%= htmlWebpackPlugin.files.chunks.services.css %>' %}">
<link rel="stylesheet" href="{% static '<%= htmlWebpackPlugin.files.chunks.contactForm.css %>' %}">
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
<script type="text/javascript" src="{% static '<%= htmlWebpackPlugin.files.chunks.home.entry %>' %}"></script>
<script type="text/javascript" src="{% static '<%= htmlWebpackPlugin.files.chunks.services.entry %>' %}"></script>
<script type="text/javascript" src="{% static '<%= htmlWebpackPlugin.files.chunks.contactForm.entry %>' %}"></script>
<script src='https://www.google.com/recaptcha/api.js?hl={{ LANGUAGE_CODE }}'></script>
{% endblock js %}

{% block body_content %}
<div class="wrapper">
    <section id="message" class="block message">
        <h1 class="jumbo">
            {% trans "There are no limits when you love your project. Expanding your project is easier than ever." %}
        </h1>
    </section>

    <section id="value" class="block value">
        <h3>{% trans "How can a website help you grow your business?" %}</h2>
        <div class="container">
            <div class="cell">
                <div id="twenty-four" class="bullet-image"></div>
                <p>24/7  Online presence </p>
            </div>
            <div class="cell">
                <div id="expansion-market" class="bullet-image"></div>
                <p>Target a wider market</p>
            </div>
            <div class="cell">
                <div id="lower-cost" class="bullet-image"></div>
                <p>Reduced marketing costs</p>
            </div>
            <div class="cell">
                <div id="insight" class="bullet-image"></div>
                <p>Consumer insight</p>
            </div>
            <div class="cell">
                <div id="customer-service" class="bullet-image"></div>
                <p>Online customer service</p>
            </div>
            <div class="cell">
                <div id="credibility" class="bullet-image"></div>
                <p>Builds business profile and credibility</p>
            </div>
            <div class="cell">
                <div id="sales" class="bullet-image"></div>
                <p>Increase sales</p>
            </div>
        </div>

        <h4>{% trans "We can make yours and your customers online experience more memorable" %}</h3>
    </section>
    <section class="divider">
        <h2>We expect the challenge</h2>
    </section>
    <section id="services" class="block services">
        <svg id="services-svg"></svg>
    </section>
    <!-- <div class="block burgundy">
        chat with us
    </div> -->
    <div id="contact" class="block contact"></div>
</div>
{% endblock %}

templates/layout.html
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
<!-- Current language: {{ LANGUAGE_CODE }} -->
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link href="https://fonts.googleapis.com/css?family=Hind:300,400,500,600,700" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">
        {% block js %}{% endblock %}
        <link rel="stylesheet" href="{% static '<%= htmlWebpackPlugin.files.chunks.layout.css %>' %}">
        {% block css %}{% endblock %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <header>
            <a href="{% url 'home:home' %}">
                <div class="logo" >Linekode</div>
            </a>
            <nav>
                <ul>
                    <li><a href="#">{% trans "Value" %}</a></li>
                    <li><a href="#">{% trans "Why?" %}</a></li>
                    <li><a href="#services">{% trans "Services" %}</a></li>
                    <li><a href="#">{% trans "Work" %}</a></li>
                </ul>
            </nav>
            <div id="language-box">
                <form action="{% url 'set_language' %} " method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />
                        {% for language in languages %}
                            <a 
                            class="{% if language.code == LANGUAGE_CODE %}selected{% endif %}" 
                            href="/{{ language.code }}{{request.get_full_path|slice:'3:' }}">
                                {{ language.code|upper }}
                            </a>
                        {% endfor %}
                </form>
            </div>
        </header>

        {% block body_content %}{% endblock %}

        <footer>
            <!--    <a href="http://twitter.com">-->
            <!--        <img src="img/twitter-wrap.png" alt="Twitter Logo" class="social-icon">-->
            <!--    </a>-->
            <!--    <a href="https://github.com/djangulo">-->
            <!--        <img src="img/GitHub-Mark.png" alt="Github Logo" class="social-icon">-->
            <!--    </a>-->
            <p>&copy; 2018 Linekode Development</p>
        </footer>
    </body>
    
    {% block bottom_page_js %}{% endblock %}
</html>